export default {
  get(iconName: string, packName = this.pack || "mdi") {
    return this.packs[packName][iconName];
  },

  packs: {
    md: {
      bold: "format_bold",
      italic: "format_italic",
      underline: "format_underlined",
      strike: "format_strikethrough",
      color: "format_color_text",
      highlight: "format_color_fill",
      h1: "mdi-format-header-1",
      h2: "mdi-format-header-2",
      h3: "mdi-format-header-3",
      p: "mdi-format-paragraph",
      left: "format_align_left",
      center: "format_align_center",
      right: "format_align_right",
      justify: "format_align_justify",
      bulletList: "format_list_bulleted",
      orderedList: "format_list_numbered",
      checkbox: "ballot",
      link: "link",
      image: "image",
      gif: "",
      video: "videocam",
      emoji: "tag_faces",
      blockquote: "format_quote",
      rule: "horizontal_rule",
      code: "code",
      codeBlock: "terminal",
      clear: "format_clear",
      search: "search",
    },
    mdi: {
      bold: "mdi-format-bold",
      italic: "mdi-format-italic",
      underline: "mdi-format-underline",
      strike: "mdi-format-strikethrough",
      color: "mdi-palette",
      highlight: "mdi-grease-pencil",
      h1: "mdi-format-header-1",
      h2: "mdi-format-header-2",
      h3: "mdi-format-header-3",
      p: "mdi-format-paragraph",
      left: "mdi-format-align-left",
      center: "mdi-format-align-center",
      right: "mdi-format-align-right",
      justify: "mdi-format-align-justify",
      bulletList: "mdi-format-list-bulleted",
      orderedList: "mdi-format-list-numbered",
      checkbox: "mdi-format-list-checkbox",
      link: "mdi-link",
      image: "mdi-image",
      gif: "mdi-file-gif-box",
      video: "mdi-video",
      emoji: "mdi-emoticon-outline",
      blockquote: "mdi-format-quote-open",
      rule: "mdi-minus",
      code: "mdi-code-tags",
      codeBlock: "mdi-code-braces-box",
      clear: "mdi-format-clear",
      search: "mdi-magnify",
    },
    fa: {
      bold: "fa-bold",
      italic: "fa-italic",
      underline: "fa-underline",
      strike: "fa-strikethrough",
      color: "fa-paint-brush",
      highlight: "fa-highlighter",
      h1: "mdi-format-header-1",
      h2: "mdi-format-header-2",
      h3: "mdi-format-header-3",
      p: "mdi-format-paragraph",
      left: "fa-align-left",
      center: "fa-align-center",
      right: "fa-align-right",
      justify: "fa-align-justify",
      bulletList: "fa-list-ul",
      orderedList: "fa-list-ol",
      checkbox: "fa-check",
      link: "fa-link",
      image: "fa-image",
      gif: "",
      video: "fa-video",
      emoji: "fa-regular fa-face-grin",
      blockquote: "fa-quote-left",
      rule: "fa-minus",
      code: "fa-code",
      codeBlock: "fa-code",
      clear: "fa-text-slash",
      search: "fa-search",
    },
  },
};
