export default {
  a: ["href", "title", "target"],
  span: ["style", "data-type", "class", "data-label", "data-id"],
  blockquote: ["style"],
  p: ["style"],
  hr: [],
  pre: [],
  code: [],
  strong: [],
  img: ["src", "alt", "title"],
  label: ["contenteditable"],
  input: ["type", "value"],
  div: ["class"],
  iframe: ["src", "allowfullscreen"],
  em: [],
  s: [],
  mark: [],
  h1: [],
  h2: [],
  h3: [],
  ul: ["class", "data-type"],
  li: ["data-checked"],
  ol: [],
  u: [],
  tr: ["class", "style"],
  td: ["class", "style"],
  th: ["class", "style"],
  tbody: ["class", "style"],
  table: ["class", "style"],
  br: [],
};
